apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: linode-managed-disk
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: linode-block-storage
  resources:
    requests:
      storage: 10Gi
